### ISSUE TITLE
do we have npm package follow module system with import/export ?

### ISSUE THREAD

**Issue by anvotrinh** [stewartlord/identicon.js#10]
I'm going to use this with React, I think it should be available in npm and included all it's dependencies in package.json

**Comment by stewartlord** [comment]
Hmm.. It is in npm and here aren't any external dependencies. What problem are you seeing?

**Comment by anvotrinh** [comment]
You need to export module from identicon.js so i can import them from my js file.
If you use window.Identicon, it can only work on browser. I want it work for both server and browser

**Comment by lkmtri** [comment]
`this.code`

**Comment by stewartlord** [comment]
Got it, I will take look.

**Comment by stewartlord** [comment]
Hi @votinhaooo, I just committed a change that should allow Identicon.js to work in the browser or via NPM require(). I hope it works for you. Let me know if we can close this issue.

**Comment by mitar** [comment]
Hm, when using it as a NPM module I am getting "PNGlib is not defined" error?

**Comment by stewartlord** [comment]
Oh no! I see your PR, thanks :)
