### ISSUE TITLE
How to increase grid size?

### ISSUE THREAD

**Issue by RobinLinus** [stewartlord/identicon.js#13]
By default it is a 5x5 "pixel" grid. How do you increase it to, say 7x7 ?

**Comment by stewartlord** [comment]
Hi Robin, at the moment it doesn't support any other grid size. The logic is fairly specifically designed for a 5x5 grid. I think it could be applied to a 7x7 grid though. 9x9 would exceed the number of available characters in a standard hash, so you'd need to come up with a different approach if you wanted to make it larger. I'd gladly accept a PR :)
