### ISSUE TITLE
Tagging Releases

### ISSUE THREAD

**Issue by McTalian** [stewartlord/identicon.js#15]
Is there anyway you can start tagging releases? One of our projects relies on this library and the recent updates have caused our builds to fail unexpectedly after unrelated changes.

**Comment by stewartlord** [comment]
Hey Robert, I wasn't aware that I committed a change that broke backwards compatibility. Can you please share the details?

**Comment by McTalian** [comment]
Sorry for the delay! Lost track of time

Whatever changed and caused #12 to occur is what messed us up in particular. We were able to reorder the dependencies (an easy fix albeit not an easy investigation) and get our builds to pass again. So that is a fairly minor example, but I tend to err on the side of "specify dependency releases so that my builds are identical until I choose to upgrade the dependencies."

**Comment by stewartlord** [comment]
Now tagging releases 👍
