### ISSUE TITLE
Canvas or SVG implementation

### ISSUE THREAD

**Issue by rugk** [stewartlord/identicon.js#17]
Creating PNG images may not be such an up-to-date implementation. Do you know an implementation, which e.g. uses SVG or HTML5 canvas to show the image?

Or would you always choose this PNG implementation? If so, why?

**Comment by rugk** [comment]
Or do you have plans to implement this in this lib?

**Comment by stewartlord** [comment]
SVG would make a lot of sense. It's also quite easy to make SVGs. I like this idea. Do you want to make a PR for it?

**Comment by rugk** [comment]
No, I have no idea how to do it. This was just a feature suggestion...

**Comment by stewartlord** [comment]
Ok, well it's a good idea! If I can find the time I would like to do it.

**Comment by redboul** [comment]
be carefull, it seems there are some SVG issues with IE... sandstorm-io/sandstorm#2268

**Comment by stewartlord** [comment]
Added a PR for this #18. Only just seeing your comment re: sandstorm-io. After I decided to code it. Heh, figures 😄

**Comment by stewartlord** [comment]
Implemented in v2.0.0!
