### ISSUE TITLE
Pink square for any hash

### ISSUE THREAD

**Issue by matolivier** [stewartlord/identicon.js#20]
Hi,

It looks the only identicon I can generate is a pink square and I have no idea why:
![identicon-issue](https://cloud.githubusercontent.com/assets/18326674/20463374/49854fbe-af31-11e6-9b16-2cb1b3118898.png)

I can see my hash changing in page code and I have no related error in console:
```
<script src="/themes/Bootstrap3-custom/js/pnglib.js"></script>
<script src="/themes/Bootstrap3-custom/js/identicon.js"></script>
...
<script>
  var hash = "tg";
  var data = new Identicon(hash).toString();
  document.write('<img src="data:image/png;base64,' + data + '">');
</script>
...
<script>
  var hash = "test";
  var data = new Identicon(hash).toString();
  document.write('<img src="data:image/png;base64,' + data + '">');
</script>
...
<script>
  var hash = "maoli";
  var data = new Identicon(hash).toString();
  document.write('<img src="data:image/png;base64,' + data + '">');
</script>
```

Did I missed something?

**EDIT**

Removing the hash (var data = new Identicon().toString();) gives me correct identicons. If I use hash a put whatever value (php or not php generated) I have the pink square.

**Comment by stewartlord** [comment]
Hi @matolivier, it's expecting a hash like `d3b07384d113edec49eaa6238ad5ff00`. It looks like the docs are not very clear on this at all. I'm not sure why they were changed to say 'Any unicode string', but it is most definitely not going to work with any unicode string. It needs to be hexadecimal for the math to work out.

I will update the docs!

**Comment by stewartlord** [comment]
Ok, docs are fixed. Let me know if you are still having trouble. Sorry!

**Comment by matolivier** [comment]
Hi @stewartlord,

Indeed, after some tweaking it works far better with long hexadecimal hash!

Thank you.
