### ISSUE TITLE
Update package.json description

### ISSUE THREAD

**Issue by buildbreakdo** [stewartlord/identicon.js#29]
Description is out of date:

`"description": "GitHub-style identicons in JS with no server-side processing.",`

This shows up as a big banner on NPM and in search results which could lead people not to use the package (states no SSR but there is SSR). See here https://www.npmjs.com/package/identicon.js.

**Comment by stewartlord** [comment]
Good catch! Any suggested wording?

**Comment by buildbreakdo** [comment]
@stewartlord Identicon generator able to render Github style avatars on server or client? Another heads up, also saw a boost in traffic on a lib of mine when adding github tags, might be something to think about.

**Comment by stewartlord** [comment]
Belated thanks @buildbreakdo, just updated the description 👍
