### ISSUE TITLE
Setting margin to 0 does not work

### ISSUE THREAD

**Issue by buildbreakdo** [stewartlord/identicon.js#31]
Margin settings are not being parsed correctly. Assume it is because `0` is evaluated as a falsey value thus letting the `.2` default take over, `0.000001` does indeed work.

```
{
        size: 40,
        margin: 0,
        background: [250, 250, 250, 255],
        format: 'svg'
}
```

**Comment by stewartlord** [comment]
Nice catch! I'll fix this up.

**Comment by stewartlord** [comment]
#33
