### ISSUE TITLE
Included createHashFromString doesn't do what it says it does

### ISSUE THREAD

**Issue by aaronjensen** [stewartlord/identicon.js#32]
Maybe I'm doing something wrong, but as far as I can tell, `createHashFromString` returns a base 10 number as a string:  

```js
createHashFromString((new Date()).toISOString())
"1925920777"
```

This ends up not providing enough info digits for random identicon generation. I wonder if https://github.com/emn178/js-sha1 should be used?

**Comment by stewartlord** [comment]
Sorry for the late reply. I will look into this issue 👍

**Comment by stewartlord** [comment]
It looks to me like it never worked! Do you need this feature? If not I think I will just remove it and make hash required again.

**Comment by aaronjensen** [comment]
works for me.

**Comment by stewartlord** [comment]
#34
