### ISSUE TITLE
Generate hash instead of throw

### ISSUE THREAD

**Issue by buildbreakdo** [stewartlord/identicon.js#37]
Bit by some bad data (totally my fault), what was returned from the API was not a string and this line ended up crashing the app out. If a throw is present, means users have to wrap any call to this API in a try-catch; this is not explicitly mentioned anywhere. Likely best to avoid identicon generation failures generating 500/server errors, if it was a critical portion of an app, then may be a different conclusion.

What are thoughts around generating the hash if it is not present and extending the string to 15 chars if length < 15? More defensive approach.

```
        if (typeof(hash) !== 'string' || hash.length < 15) {
            throw 'A hash of at least 15 characters is required.';
        }
```

**Comment by stewartlord** [comment]
Hey Josh, that sounds okay to me! It might be a bit magical to do this silently. How do you feel about putting it behind an option flag? Not sure what to call that option..

**Comment by stewartlord** [comment]
Some ideas.. `makeHash`, `fixHash`, `randomHash`, `forgiveHash`

**Comment by theaquarium** [comment]
Maybe something like `autoHashInput` or `generateHash`. This would actually be very useful. The option could allow you to input text instead of a hash. This can be done with [jsSHA](https://github.com/Caligatio/jsSHA). I don't know if you know about [identicon.net](identicon.net) but that uses jsSHA. Here's the code it uses for generating the icon:

```js
function get_identicon (text) {
    var salt = $("#salt")[0].value;
    var rounds = Number($("#rounds")[0].value);
    var size = Number($("#size")[0].value);
    var outputType = $('input[name=outputType]:checked')[0].value;
    var hashtype = $('input[name=hashVariant]:checked')[0].value;
    var shaObj = new jsSHA(text+salt, "TEXT");
    var hash = shaObj.getHash(hashtype, outputType,rounds);
    var data = new Identicon(hash, size).toString();
    $("#show_identicon")[0].src='data:image/png;base64,' + data;
}
```

**Comment by stewartlord** [comment]
I like `generateHash` for an option name. I'm a bit reluctant to add a dependency for it since the current dist doesn't require anything.

**Comment by buildbreakdo** [comment]
@stewartlord Think this should be handled automatically, see APIs/Libraries as contracts. We promise to do X for you. Contract of this API is give us a string and we will give you an identicon. The contract should be fulfilled regardless of string length, the end user does not care about details of underlying libraries that require a 15 char hash (and they shouldn't). Identicon is a visual identity attached to a string, that is all. 

The underlying mechanism/requirements to generate this behind the scenes should be hidden from API users. If the user _must_ transform a string to use this API then this should be handled internally within the API automatically (even an empty string should have a visual identity/fingerprint), no value in requiring a user to do an extra step that must happen and can easily be automatically handled internally. Cheers

**Comment by theaquarium** [comment]
I agree with @buildbreakdo however this shouldn't be always on. I think this should be toggleable as an option and if the user disables this feature and gives an incompatible string, you should print a warning and hash anyway.

**Comment by Robien** [comment]
I made a PR #43 feel free to comment it.

**Comment by stewartlord** [comment]
Thanks everyone, I'll look at getting a fix in shortly. @Robien I'll check out your PR :+1:

**Comment by stewartlord** [comment]
@buildbreakdo I definitely agree we should uphold the contract. In this case the contract is documented as "hash - A hexadecimal string of 15+ characters that will be used to generate the image."

However, maybe we should relax the contract.

**Comment by rasikat86** [comment]
Any idea when this will be merged in?

**Comment by stewartlord** [comment]
If anyone would like to support a fork with this feature I would be happy to link to it from the README on this repo.
