### ISSUE TITLE
Following github style

### ISSUE THREAD

**Issue by chamerling** [stewartlord/identicon.js#4]
Hi @stewartlord,

Do you want to strictly follow github identicon style or are you open to pull requests which adds options to have some different behavior (colors, etc)?

Thanks

**Comment by stewartlord** [comment]
Hi Christophe, I really like the idea of options for different behaviors. I saw an article recently that talked about this http://darrennewton.com/2015/01/04/deterministic-pixels/. 

Starting small and keeping the current behavior as default would be good.
Thanks!
