### ISSUE TITLE
Crash when size set to big value

### ISSUE THREAD

**Issue by geekadomicile** [stewartlord/identicon.js#45]
...or when inputted too fast :)

**Comment by stewartlord** [comment]
Hi @geekadomicile do you have repro steps? Thanks!

**Comment by geekadomicile** [comment]
Sure thing 👍 
Go to http://identicon.net/
Set Advanced/Size field to "21000" or more
There, the app crashes.

**Comment by stewartlord** [comment]
Closing this as it appears to be a problem with identicon.net
