### ISSUE TITLE
Foreground color producing no identicon.

### ISSUE THREAD

**Issue by ialexop** [stewartlord/identicon.js#49]
I've been trying to generate an identicon, passing `[255, 69, 0, 1]` as the rgba color (it's `#ff4500`), but the produced identicon files don't have any identicon. I tried with black as per the documentation, and it worked. 

- Node.js: 12.14 (Docker on Mac)
- Identicon library: 2.3.3

Thanks in advance! And thanks for a great library 🙏

**Comment by stewartlord** [comment]
Hi @ialexop, I think the issue is that the identicon is effectively invisible due to the low opacity `1`. Try `[255, 69, 0, 255]`.

Hope that helps!

**Comment by ialexop** [comment]
Oh, I see, didn't think about that. Will definitely try that out and let you know. Thanks @stewartlord 🙏
