### ISSUE TITLE
do we have option to use dark style in default background?

### ISSUE THREAD

**Issue by namnm** [stewartlord/identicon.js#8]

**Comment by stewartlord** [comment]
Hi namm, we do not yet. There is a pull request for this that is in progress. If you are able to help move it along that would be appreciated.

https://github.com/stewartlord/identicon.js/pull/7

**Comment by ppuleo** [comment]
Hi @namnm, a background color option has been added in #7. If that meets your need, feel free to close this.

**Comment by stewartlord** [comment]
Seems like #7 should satisfy this. Closing
